name: Build Documentation

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-docs.yml'
      - 'src/**'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "sergio-lucas/webCamProcessor.wiki"
          path: ./wiki

      - name: Install dependencies
        run: |
          ls
          cd wiki
          ls
          yarn
          yarn docs

      - name: Commit and push changes to Wiki
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          ls
          git add .
          git commit -m "Add build artifact"
          git push
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16.18.1
      #     cache: yarn
      # - name: Checkout Wiki
      #   uses: actions/checkout@v2
      #   with:
      #     repository: sergio-lucas/webCamProcessor.wiki.git
      #     path: wiki

      # - name: Install dependencies
      #   run: |
      #     cd wiki
      #     yarn

      # - name: Commit and push changes to Wiki
      #   run: |
      #     yarn docs
      #     git config --global user.name 'github-actions'
      #     git config --global user.email 'github-actions@github.com'
      #     git add .
      #     git commit -m "Add build artifact"
      #     git push
      

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     # Test without token
      #     # github_token: ${{ secrets.GITHUB_TOKEN }}
      #     personal_token: ${{ secrets.PERSONAL_TOKEN }}
      #     publish_branch: docs
      #     # Build output to publish to the `gh-pages` branch:
      #     publish_dir: ./docs/build
      #     # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
      #     # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #     # The GH actions bot is used by default if you didn't specify the two fields.
      #     # You can swap them out with your own user credentials.
      #     user_name: github-actions[bot]
      #     user_email: 41898282+github-actions[bot]@users.noreply.github.com
