name: Build Documentation

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-docs.yml'
      - 'src/**'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "sergio-lucas/webCamProcessor.wiki"
          path: ./wiki

      - name: Install dependencies
        run: |
          cd wiki
          yarn
          yarn docs

      - name: Commit and push changes to Wiki
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          cd wiki
          git add .
          # only commit if there are changes
          git diff-index --quiet HEAD -- || git commit -m "sync from doc/"
          git push
